version: '3'
secrets:
  duckdns_token:
    file: ./secrets/duckdns-token.txt
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/caio/.config/mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/caio/.config/nextcloud:/config
      - /home/caio/nextcloud-data:/data
    ports:
      - 8081:443
    restart: unless-stopped
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/caio/.config/heimdall:/config
    ports:
      - 8082:80
      - 444:443
    restart: unless-stopped
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/caio/.config/home-assistant:/config
    ports:
      - 8123:8123
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /home/caio/.config/transmission:/config
      - /home/caio/library/torrents:/data/torrents
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /home/caio/.config/jellyfin:/config
      - /home/caio/library/media:/data/media
    ports:
      - 8096:8096
      - 7359:7359/udp 
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /home/caio/.config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /home/caio/.config/radarr:/config
      - /home/caio/library:/data
    ports:
      - 7878:7878
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /home/caio/.config/lidarr:/config
      - /home/caio/library:/data
    ports:
      - 8686:8686
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /home/caio/.config/sonarr:/config
      - /home/caio/library:/data
    ports:
      - 8989:8989
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3141:80/tcp"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - '/home/caio/.config/pihole:/etc/pihole'
      - '/home/caio/.config/dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /home/caio/.config/nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  ipfs:
    image: lscr.io/linuxserver/ipfs
    container_name: ipfs
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /home/caio/.config/ipfs:/config
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
      - 8084:80
      - 445:443
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
      - LOG_LEVEL=debug
    ports:
      - 5055:5055
    volumes:
      - /home/caio/.config/jellyseerr:/app/config
    restart: unless-stopped
  
  influxdb:
    container_name: scrutiny-influxdb
    image: influxdb:2.2
    ports:
      - '8086:8086'
    volumes:
      - '/home/caio/.config/scrutiny/influxdb:/var/lib/influxdb2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 20
  web:
    container_name: scrutiny-web
    image: 'ghcr.io/analogj/scrutiny:master-web'
    ports:
      - '8083:8080'
    volumes:
      - '/home/caio/.config/scrutiny/web:/opt/scrutiny/config'
    environment:
      SCRUTINY_WEB_INFLUXDB_HOST: 'influxdb'
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
  collector:
    container_name: scrutiny-collector
    image: 'ghcr.io/analogj/scrutiny:master-collector'
    cap_add:
      - SYS_RAWIO
    volumes:
      - '/run/udev:/run/udev:ro'
    environment:
      COLLECTOR_API_ENDPOINT: 'http://web:8080'
    depends_on:
      web:
        condition: service_healthy
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"